# Generated by Django 5.1.2 on 2024-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cantperros', models.PositiveSmallIntegerField()),
                ('empleados', models.PositiveSmallIntegerField()),
                ('telefono', models.IntegerField()),
                ('cantcomida', models.PositiveSmallIntegerField()),
                ('encargado', models.CharField(max_length=25)),
            ],
        ),
    ]
