# Generated by Django 5.1.2 on 2024-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('comportamiento', models.TextField(max_length=300, verbose_name='Comportamiento')),
                ('vacunas', models.TextField(max_length=300, verbose_name='vacunas')),
                ('sexo', models.CharField(max_length=15)),
            ],
        ),
    ]
