# Generated by Django 5.1.2 on 2024-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='fecha_ing',
            new_name='feching',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni',
            field=models.CharField(max_length=10),
        ),
    ]
