# Generated by Django 5.1.2 on 2024-11-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0002_rename_fecha_ing_empleados_feching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='salario',
            field=models.IntegerField(),
        ),
    ]
