# Generated by Django 5.1.2 on 2024-11-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encargado_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargados',
            old_name='fecha_ing',
            new_name='fechaenc',
        ),
        migrations.RemoveField(
            model_name='encargados',
            name='salario',
        ),
    ]
