# Generated by Django 5.1.2 on 2024-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargado_app', '0002_rename_fecha_ing_encargados_fechaenc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargados',
            name='dni',
            field=models.CharField(max_length=10),
        ),
    ]
