# Generated by Django 5.1.2 on 2024-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('candado', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=15)),
                ('comida', models.PositiveSmallIntegerField()),
                ('agua', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
